sudo: false
dist: trusty
language: python
python:
  - 2.7
  - 3.4
  - 3.6
addons:
  apt:
    packages:
      - libopenbabel-dev
      - swig
cache:
  pip: true

before_install:
  - pip install -r requirements.txt

install:
  - pip install .

before_script:
  - |
    export DOCS_REPO_NAME=cclib.github.io
    export DOCS_REPO_SLUG=cclib/${DOCS_REPO_NAME}
    export GH_REPO_REF=github.com/${DOCS_REPO_SLUG}.git
    export DOCS_BRANCH_NAME=gh-pages
    export DOCS_DIR="${TRAVIS_BUILD_DIR}"/doc/sphinx
    export THEME_DIR="${DOCS_DIR}"/_themes
  - install -dm755 "${THEME_DIR}"

script:
  - bash travis/run_travis_tests.sh
  - bash travis/build_docs.sh
  - |
    if [[ "${TRAVIS_BRANCH}" == master && "${TRAVIS_PULL_REQUEST}" == false ]];
    then
        bash travis/deploy_docs_travis-sphinx.sh
    fi
