language: python
python:
  - 3.2
virtualenv:
  system_site_packages: true
before_install:
  - sudo apt-get install python3-numpy
install:
  - python setup.py install
script:
  - cd test; python testall.py
