name: cclib docs

on:
  pull_request:
    branches:
      - master
    types: [closed]

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: Get docs html
      uses: actions/download-artifact@v2
      with:
        name: html-docs
        path: html-docs
    - name: Commit documentation changes
      run: |
        git clone https://github.com/cclib/cclib.git --branch gh-pages --single-branch gh-pages
        cp -r html-docs/* gh-pages/
        cd gh-pages
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Commit: ${GITHUB_SHA}" || true
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: gh-pages
        directory: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
