---
# yamllint disable rule:line-length
name: run tests and coverage

# yamllint disable-line rule:truthy
on: [push, pull_request]

jobs:
  run-tests:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        container: ['shivupa/cclib-ci:py37']
    container:
      image: ${{ matrix.container }}
    defaults:
      run:
        shell: bash -eo pipefail -l {0}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Prepare conda environment
        run: |
          echo "/env/bin" >> $GITHUB_PATH
      - name: Install cclib
        run: |
          python -m pip install .
      - name: Test with pytest
        run: |
          env | sort
          bash .github/scripts/run_pytest.bash
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          files: ./coverage-unit.xml,./coverage-regression.xml
          name: codecov-cclib
          fail_ci_if_error: true
          verbose: false
        if: matrix.container == 'shivupa/cclib-ci:py37'
