---
name: build and test nix package

# yamllint disable-line rule:truthy
on: [push, pull_request]

jobs:
  nix-build:
    runs-on: ubuntu-latest
    steps:
      # Install Nix on the runner
      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      # Pull from the cachix cache
      - uses: cachix/cachix-action@v12
        with:
          name: nix-qchem
      # Checkout of the current head in the working dir
      - uses: actions/checkout@v4
      # Build the nix package
      - name: Build nix package
        run: nix flake check -L
