---
# yamllint disable rule:line-length
name: run tests and coverage

# yamllint disable-line rule:truthy
on: [push, pull_request]

jobs:

  run-tests:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        container: ['shivupa/cclib-ci:py37']
    steps:
      - name: Install core dependencies
        shell: bash -l {0}
        run: |
          python -m pip install -r requirements.txt
      - name: Install cclib
        shell: bash -l {0}
        run: |
          which python
          python -m pip install .
      - name: Test with pytest
        shell: bash -l {0}
        run: |
          which python
          env | sort
          bash .github/scripts/run_pytest.bash
      - name: Upload coverage to Codecov
        if: matrix.container == 'shivupa/cclib-ci:py37'
        uses: codecov/codecov-action@v1
        with:
          files: ./coverage-unit.xml,./coverage-regression.xml
          name: codecov-cclib
          fail_ci_if_error: true
          verbose: false
